---
- name: Installing yum-cron
  yum:
    name: yum-cron
    state: latest

- name: Updating yum-cron configuration
  template:
    src: yum-cron.conf.j2
    dest: /etc/yum/yum-cron.conf
  notify:
    - restart yum-cron

- name: Enable yum-cron
  service:
    name: yum-cron
    state: started
    enabled: yes